name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./auth
          file: ./auth/Dockerfile
          tags: w6itec6apel/auth:latest
